DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS houses CASCADE;

CREATE TABLE houses (
  id SERIAL4 PRIMARY KEY,
  name VARCHAR(255), 
  beast VARCHAR(255)
);

CREATE TABLE students (
  id SERIAL4 PRIMARY KEY,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  age INT4,
  house INT4 REFERENCES houses(id) ON DELETE CASCADE
); 

ALTER TABLE students
DROP COLUMN house;

ALTER TABLE students
ADD house VARCHAR(255);